version: '3.8'

services:
  backend:
    container_name: nebulaops-backend
    image: chadmany20/nebulaops-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    networks:
      - nebulaops

  frontend:
    container_name: nebulaops-frontend
    image: chadmany20/nebulaops-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - backend
    networks:
      - nebulaops

networks:
  nebulaops:
    driver: bridge
